const Discord = require("discord.js");
const Canvas = require("canvas");
const fs = require("fs");
const cmd = require("node-cmd");
const config = require("./config.json");
const prefix = config.prefix;
const client = new Discord.Client();
const client2 = new Discord.Client();
const client3 = new Discord.Client();
const client4 = new Discord.Client();
const client5 = new Discord.Client();
const client6 = new Discord.Client();
const client7 = new Discord.Client();
const client8 = new Discord.Client();
const client9 = new Discord.Client();
const client10 = new Discord.Client();
const client11 = new Discord.Client();
const client12 = new Discord.Client();
const client13 = new Discord.Client(); 
const client14 = new Discord.Client();
const client15 = new Discord.Client();
const client16 = new Discord.Client();
const client17 = new Discord.Client();
const client18 = new Discord.Client();
const client19 = new Discord.Client(); 
const client20 = new Discord.Client();
const client21 = new Discord.Client();
const client22 = new Discord.Client();
const client23 = new Discord.Client();
const client24 = new Discord.Client();
const client25 = new Discord.Client();
const client26 = new Discord.Client();
const client27 = new Discord.Client();
const client28 = new Discord.Client();
const client29 = new Discord.Client();
const client30 = new Discord.Client();
const client31 = new Discord.Client();
const client32 = new Discord.Client();
const client33 = new Discord.Client();
const client34 = new Discord.Client();
const client35 = new Discord.Client();
const client36 = new Discord.Client();
const client37 = new Discord.Client();
const client38 = new Discord.Client();
const client39 = new Discord.Client();
const client40 = new Discord.Client();
const client41 = new Discord.Client();
const client42 = new Discord.Client();
const client43 = new Discord.Client();
const client44 = new Discord.Client();
const client45 = new Discord.Client();
const client46 = new Discord.Client();
const client47 = new Discord.Client();
const client48 = new Discord.Client();
const client49 = new Discord.Client();
const client50 = new Discord.Client();
const client51 = new Discord.Client();
const client52 = new Discord.Client();
const client53 = new Discord.Client();
const client54 = new Discord.Client();
const client55 = new Discord.Client();
const client56 = new Discord.Client();
const client57 = new Discord.Client();
const client58 = new Discord.Client();
const client59 = new Discord.Client();
const client60 = new Discord.Client();
const client61 = new Discord.Client();
const client62 = new Discord.Client();
const client63 = new Discord.Client();
const client64 = new Discord.Client();
const client65 = new Discord.Client();
const client66 = new Discord.Client();
const client67 = new Discord.Client();
const client68 = new Discord.Client();
const client69 = new Discord.Client();
const client70 = new Discord.Client();
const client71 = new Discord.Client();
const client72 = new Discord.Client();
const client73 = new Discord.Client();
const client74 = new Discord.Client();
const client75 = new Discord.Client();
const client76 = new Discord.Client();
const client77 = new Discord.Client();
const client78 = new Discord.Client();
const client79 = new Discord.Client();
const client80 = new Discord.Client();
const client81 = new Discord.Client();
const client82 = new Discord.Client();
const client83 = new Discord.Client();
const client84 = new Discord.Client();
const client85 = new Discord.Client();
const client86 = new Discord.Client();
const client87 = new Discord.Client();
const client88 = new Discord.Client();
const client89 = new Discord.Client();
const client90 = new Discord.Client();
const client91 = new Discord.Client();
const client92 = new Discord.Client();
const client93 = new Discord.Client();
const client94 = new Discord.Client();
const client95 = new Discord.Client();
const client96 = new Discord.Client();
const client97 = new Discord.Client();
const client98 = new Discord.Client();
const client99 = new Discord.Client();
const client100 = new Discord.Client();
const client101 = new Discord.Client();
const client102 = new Discord.Client();
const client103= new Discord.Client();
const client104 = new Discord.Client();
const client105 = new Discord.Client();
const client106 = new Discord.Client();
const client107 = new Discord.Client();
const client108 = new Discord.Client();
const client109 = new Discord.Client();
const client110 = new Discord.Client();
const client111 = new Discord.Client();
const client112 = new Discord.Client();
const client113 = new Discord.Client();
const client114 = new Discord.Client();
const client115 = new Discord.Client();
const client116 = new Discord.Client();
const client117 = new Discord.Client();
const client118 = new Discord.Client();
const client119 = new Discord.Client();
const client120 = new Discord.Client();
const client121 = new Discord.Client();
const client122 = new Discord.Client();
const client123 = new Discord.Client();
const client124 = new Discord.Client();
const client125 = new Discord.Client();
const client126 = new Discord.Client();
const client127 = new Discord.Client();
const client128 = new Discord.Client();
const client129 = new Discord.Client();
const client130 = new Discord.Client();
const client131 = new Discord.Client();
const client132 = new Discord.Client();
const client133 = new Discord.Client();
const client134 = new Discord.Client();
const client135 = new Discord.Client();
const client136 = new Discord.Client();
const client137 = new Discord.Client();
const client138 = new Discord.Client();
const client139 = new Discord.Client();
const client140 = new Discord.Client();
const client141 = new Discord.Client();
const client142 = new Discord.Client();
const client143 = new Discord.Client();
const client144 = new Discord.Client();
const client145 = new Discord.Client();
const client146 = new Discord.Client();
const client147 = new Discord.Client();
const client148 = new Discord.Client();
const client149 = new Discord.Client();
const client150 = new Discord.Client();
const client151 = new Discord.Client();
const client152 = new Discord.Client();
const client153 = new Discord.Client();
const client154 = new Discord.Client();
const client155 = new Discord.Client();
const client156 = new Discord.Client();
const client157 = new Discord.Client();
const client158 = new Discord.Client();
const client159 = new Discord.Client();
const client160 = new Discord.Client();
const client161 = new Discord.Client();
const client162 = new Discord.Client();
const client163 = new Discord.Client();
const client164 = new Discord.Client();
const client165 = new Discord.Client();
const client166 = new Discord.Client();
const client167 = new Discord.Client();
const client168 = new Discord.Client();
const client169 = new Discord.Client();
const client170 = new Discord.Client();
const client171 = new Discord.Client();
const client172 = new Discord.Client();
const client173 = new Discord.Client();
const client174 = new Discord.Client();
const client175 = new Discord.Client();
const client176 = new Discord.Client();
const client177 = new Discord.Client();
const client178 = new Discord.Client();
const client179 = new Discord.Client();
const client180 = new Discord.Client();
const client181 = new Discord.Client();
const client182 = new Discord.Client();
const client183 = new Discord.Client();
const client184 = new Discord.Client();
const client185 = new Discord.Client();
const client186 = new Discord.Client();
const client187 = new Discord.Client();
const client188 = new Discord.Client();
const client189 = new Discord.Client();
const client190 = new Discord.Client();
const client191 = new Discord.Client();
const client192 = new Discord.Client();
const client193 = new Discord.Client();
const client194 = new Discord.Client();
const client195 = new Discord.Client();
const client196 = new Discord.Client();
const client197 = new Discord.Client();
const client198 = new Discord.Client();
const client199 = new Discord.Client();
const client200 = new Discord.Client();
const client201 = new Discord.Client();
const client202 = new Discord.Client();
const client203 = new Discord.Client();
const client204 = new Discord.Client();
const client205 = new Discord.Client();
const client206 = new Discord.Client();
const client207 = new Discord.Client();
const client208 = new Discord.Client();
const client209 = new Discord.Client();
const client210 = new Discord.Client();
const client211 = new Discord.Client();
const client212 = new Discord.Client();
const client213 = new Discord.Client();
const client214 = new Discord.Client();
const client215 = new Discord.Client();
const client216 = new Discord.Client();
const client217 = new Discord.Client();
const client218 = new Discord.Client();
const client219 = new Discord.Client();
const client220 = new Discord.Client();
const client221 = new Discord.Client();
const client222 = new Discord.Client();
const client223 = new Discord.Client();
const client224 = new Discord.Client();
const client225 = new Discord.Client();
const client226 = new Discord.Client();
const client227 = new Discord.Client();
const client228 = new Discord.Client();
const client229 = new Discord.Client();
const client230 = new Discord.Client();
const client231 = new Discord.Client();
const client232 = new Discord.Client();
const client233 = new Discord.Client();
const client234 = new Discord.Client();
const client235 = new Discord.Client();
const client236 = new Discord.Client();
const client237 = new Discord.Client();
const client238 = new Discord.Client();
const client239 = new Discord.Client();
const client240 = new Discord.Client();
const client241 = new Discord.Client();
const client242 = new Discord.Client();
const client243 = new Discord.Client();
const client244 = new Discord.Client();
const client245 = new Discord.Client();
const client246 = new Discord.Client();
const client247 = new Discord.Client();
const client248 = new Discord.Client();
const client249 = new Discord.Client();
const client250 = new Discord.Client();
const client251 = new Discord.Client();
const client252 = new Discord.Client();
const client253 = new Discord.Client();
const client254 = new Discord.Client();
const client255 = new Discord.Client();
const client256 = new Discord.Client();
const client257 = new Discord.Client();
const client258 = new Discord.Client();
const client259 = new Discord.Client();
const client260 = new Discord.Client();
const client261 = new Discord.Client();
const client262 = new Discord.Client();
const client263 = new Discord.Client();
const client264 = new Discord.Client();
const client265 = new Discord.Client();
const client266 = new Discord.Client();
const client267 = new Discord.Client();
const client268 = new Discord.Client();
const client269 = new Discord.Client();
const client270 = new Discord.Client();
const client271 = new Discord.Client();
const client272 = new Discord.Client();
const client273 = new Discord.Client();
const client274 = new Discord.Client();



const help = `**
كۆمانده‌كان:

بۆ زیاد كردنی ڕیاكشن
$react <Channel ID> <Message ID> <Emoji>

بۆ هێنانه‌ ڤۆیسی هه‌موو بۆته‌كان
$join**`;


client.on("message", async message => {
  if (message.content === prefix + "reset") {
    if (!dinfo.owner.includes(message.author.id)) return; 
    dinfo.serverid = "NONE";
    dinfo.channelid = "NONE";
    dinfo.timespam = "NONE"; //
    dinfo.timestop = "NONE";
    message.channel.send(`**⚠️ restsettings , <@${dinfo.owner}>**`);
    fs.writeFile("./data.json", JSON.stringify(dinfo), function(a) {
      if (a) throw a;
    });
    await cmd.run("refresh"); // 
    
  }
});
// ======= [ Console LOG    ] ======== //
client.on("ready", () => {
  console.log(`im online all account`);
 
});

client.login("");
client2.login("");
client3.login("");
client4.login("");
client5.login("");
client6.login("");
client7.login("");
client8.login("");
client9.login("");
client10.login("");
client11.login("");
client12.login("");
client13.login("");
client14.login("");
client15.login("");
client16.login("");
client17.login("");
client18.login("");
client19.login("");
client20.login("");
client21.login("");
client22.login("");
client23.login("");
client24.login("");
client25.login("");
client26.login("");
client27.login("");
client28.login("");
client29.login("");
client30.login("");
client31.login("");
client32.login("");
client33.login("");
client34.login("");
client35.login("");
client36.login("");
client37.login("");
client38.login("");
client39.login("");
client40.login("");
client41.login("");
client42.login("");
client43.login("");
client44.login("");
client45.login("");
client46.login("");
client47.login("");
client48.login("");
client49.login("");
client50.login("");
client51.login("");
client52.login("");
client53.login("");
client54.login("");
client55.login("");
client56.login("");
client57.login("");
client58.login("");
client59.login("");
client60.login("");
client61.login("");
client62.login("");
client63.login("");
client64.login("");
client65.login("");
client66.login("");
client67.login("");
client68.login("");
client69.login("");
client70.login("");
client71.login("");
client72.login("");
client73.login("");
client74.login("");
client75.login("");
client76.login("");
client77.login("");
client78.login("");
client79.login("");
client80.login("");
client81.login("");
client82.login("");
client83.login("");
client84.login("");
client85.login("");
client86.login("");
client87.login("");
client88.login("");
client89.login("");
client90.login("");
client91.login("");
client92.login("");
client93.login("");
client94.login("");
client95.login("");
client96.login("");
client97.login("");
client98.login("");
client99.login("");
client100.login("");
client101.login("");
client102.login("");
client103.login("");
client104.login("");
client105.login("");
client106.login("");
client107.login("");
client108.login("");
client109.login("");
client110.login("");
client111.login("");
client112.login("");
client113.login("");
client114.login("");
client115.login("");
client116.login("");
client117.login("");
client118.login("");
client119.login("");
client120.login("");
client121.login("");
client122.login("");
client123.login("");
client124.login("");
client125.login("");
client126.login("");
client127.login("");
client128.login("");
client129.login("");
client130.login("");
client131.login("");
client132.login("");
client133.login("");
client134.login("");
client135.login("");
client136.login("");
client137.login("");
client138.login("");
client139.login("");
client140.login("");
client141.login("");
client142.login("");
client143.login("");
client144.login("");
client145.login("");
client146.login("");
client147.login("");
client148.login("");
client149.login("");
client150.login("");
client151.login("");
client152.login("");
client153.login("");
client154.login("");
client155.login("");
client156.login("");
client157.login("");
client158.login("");
client159.login("");
client160.login("");
client161.login("");
client162.login("");
client163.login("");
client164.login("");
client165.login("");
client166.login("");
client167.login("");
client168.login("");
client169.login("");
client170.login("");
client171.login("");
client172.login("");
client173.login("");
client174.login("");
client175.login("Y");
client176.login("");
client177.login("");
client178.login("");
client179.login("");
client180.login("");
client181.login("");
client182.login("");
client183.login("");
client184.login("");
client185.login("");
client186.login("");
client187.login("");
client188.login("");
client189.login("");
client190.login("");
client192.login("");
client193.login("");
client194.login("");
client195.login("");
client196.login("");
client197.login("");
client198.login("");
client199.login("");
client200.login("");
client201.login("");
client202.login("");
client203.login("");
client204.login("");
client205.login("");
client206.login("");
client207.login("");
client208.login("");
client209.login("");
client210.login("");
client211.login("");
client212.login("");
client213.login("");
client214.login("");
client215.login("");
client216.login("");
client217.login("");
client218.login("");
client219.login("");
client220.login("");
client221.login("");
client222.login("");
client223.login("");
client224.login("");
client225.login("");
client226.login("");
client227.login("");
client228.login("");
client229.login("");
client230.login("");
client231.login("");
client232.login("");
client233.login("");
client234.login("");
client235.login("");
client236.login("");
client237.login("");
client238.login("");
client239.login("");
client240.login("");
client241.login("");
client242.login("");
client243.login("");
client244.login("");
client245.login("");
client246.login("");
client247.login("");
client248.login("");
client249.login("");
client250.login("");
client251.login("");
client252.login("");
client253.login("");
client254.login("");
client255.login("");
client256.login("");
client257.login("");
client258.login("");
client259.login("");
client260.login("");
client261.login("");
client262.login("");
client263.login("");
client264.login("");
client265.login("");
client266.login("");
client267.login("");
client268.login("");
client269.login("");
client270.login("");
client271.login("");
client272.login("");
client273.login("");
client274.login("");